services:
  backend:
    build: .
    volumes:
      - storage_data:/var/www/html/storage
      - public_data:/var/www/html/public
    environment:
      - DB_CONNECTION=mysql  # ADD THIS!
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=petmatch
      - DB_USERNAME=root
      - DB_PASSWORD=secret  
      - APP_KEY=base64:d+zjTI5mkrXkY2MDplavlliBZY7CPX1c144dTjqeU6M=
      - SEED_DATABASE=true
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - public_data:/var/www/html/public:ro
      - storage_data:/var/www/html/storage:ro
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: petmatch
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      timeout: 20s
      retries: 10
      interval: 5s
  frontend:
    build: ../frontend  # Changed from ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - nginx
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
      
volumes:
  mysql_data:
  storage_data:
  public_data: